# autofloods/utils/__init__.py

# import required libraries
import datetime, glob, os, re
import logging
import time
import concurrent.futures
import pandas as pd
import geopandas as gpd
import rasterio
from shapely.geometry import Polygon
import rioxarray
from rioxarray import merge as rioxarray_merge
import numpy as np
import xarray as xr

logger = logging.getLogger(__name__)

# DEFINE constants
#INDIA_GRID_SHAPEFILE_PATH = r'resources/india_utm_fishnet.gpkg'
# NOTE: no module-level auth/catalog global here anymore. Data-source
# access (search, DEM, signing) now goes through autofloods.sources.STACSource
# implementations (see autofloods.sources.MPCSource), constructed and
# authenticated lazily on first use rather than at import time.

# Bounded GDAL HTTP timeout/retry policy for reading remote rasters (COGs).
# Without this, GDAL's default HTTP behavior has no bounded timeout, so a
# stalled connection to a remote asset (e.g. an MPC/Azure Blob Storage href)
# can hang a job indefinitely, consuming near-zero CPU the whole time --
# this is what actually happened to job 1078026 (58 minutes of silence,
# then all its output appeared in the last ~20 seconds before the SLURM
# time limit killed it).
GDAL_HTTP_ENV = dict(
    GDAL_HTTP_CONNECTTIMEOUT=15,
    GDAL_HTTP_TIMEOUT=30,
    GDAL_HTTP_MAX_RETRY=3,
    GDAL_HTTP_RETRY_DELAY=5,
)

# MGRS latitude band letters split by hemisphere -- bands C-M cover
# 80S-0 (Southern Hemisphere), N-X cover 0-84N (Northern Hemisphere).
# See autofloods.grid._latitude_band for the same table used to
# compute a zone string's band letter from a real latitude when a
# grid is generated by autofloods.grid.generate_grid.
_NORTHERN_MGRS_BANDS = set('NPQRSTUVWX')
_SOUTHERN_MGRS_BANDS = set('CDEFGHJKLM')


def zone_to_epsg(zone):
    """
    Resolve a grid_shapefile `zone` string (UTM zone number + MGRS
    latitude-band letter, e.g. "45R" or "45C") to the correct UTM EPSG
    code: EPSG:326<zone> for the Northern Hemisphere (bands N-X),
    EPSG:327<zone> for the Southern Hemisphere (bands C-M).

    Centralizes what used to be `'EPSG:326{}'.format(zone[:-1])`
    hardcoded independently in several places (autofloods.__init__'s
    project_flood_raster, preprocessing.reproject_clip_stac,
    preprocessing.clip_xarray_using_id, utils.gpd_to_json) -- all of
    which silently assumed the Northern Hemisphere regardless of the
    zone's actual band letter. This was never hit in production (the
    Bihar/India dataset this pipeline was built and tested against is
    entirely Northern Hemisphere), but produced a wrong UTM CRS
    (mirrored across the equator) for any Southern-Hemisphere AOI.
    """
    # Zero-padded to 2 digits: EPSG UTM zone codes are 326<01-60> /
    # 327<01-60>, e.g. zone 7 north is EPSG:32607, not EPSG:3267 --
    # the latter happens to be a real, unrelated, valid EPSG code
    # (not an error), so an unpadded single-digit zone number would
    # silently resolve to the wrong CRS entirely rather than raising.
    zone_number = f"{int(zone[:-1]):02d}"
    band = zone[-1].upper()
    if band in _NORTHERN_MGRS_BANDS:
        prefix = '326'
    elif band in _SOUTHERN_MGRS_BANDS:
        prefix = '327'
    else:
        raise ValueError(
            f"Unrecognized MGRS latitude band {band!r} in zone {zone!r} "
            f"-- expected one of "
            f"{''.join(sorted(_NORTHERN_MGRS_BANDS | _SOUTHERN_MGRS_BANDS))}."
        )
    return f'EPSG:{prefix}{zone_number}'


def default_max_workers():
    """
    Default thread pool size for CPU-bound concurrent per-scene
    reprojection (see preprocessing.reproject_clip_stac/stack_images,
    flood_mapper.prepare_wet_scenes) when the caller doesn't specify one
    explicitly: (available CPUs - 1), leaving one CPU as headroom for the
    main thread/OS/other work on the node, rather than a number hardcoded
    for one particular cluster's job size.

    Prefers SLURM_CPUS_PER_TASK -- the actual per-job CPU allocation on a
    shared cluster node -- over os.cpu_count(), which reports the WHOLE
    NODE's CPU count under SLURM regardless of --cpus-per-task (e.g. 72
    on a shared node even for an 8-CPU job; this mismatch was found while
    benchmarking this exact parallelization change). Falls back to
    os.cpu_count() when not running under SLURM (e.g. a laptop or a
    non-SLURM server), so this works as a sensible default on any system,
    not just this project's own cluster.
    """
    ncpu = int(os.environ.get('SLURM_CPUS_PER_TASK', os.cpu_count() or 1))
    return max(1, ncpu - 1)


def open_rasterio_with_retry(href, overview_level=None, masked=True, max_attempts=5, backoff_seconds=20, bbox=None):
    """
    Open a (possibly remote) raster with rioxarray, under a bounded GDAL
    HTTP timeout/retry policy (see GDAL_HTTP_ENV) plus an application-level
    retry loop on top, so a single stalled or transiently-failed request
    doesn't hang or kill an entire tile-year job.

    Parameters
    ----------
    href            : str or callable
                      URL or path to open. Pass a zero-arg callable instead
                      of a plain string when the href can go stale between
                      attempts (e.g. a time-limited signed URL) -- it is
                      called again before every attempt, including the
                      first, so each attempt gets a freshly-minted href
                      rather than retrying one that may have expired
                      during an earlier attempt's wait. A plain string is
                      still accepted for hrefs that don't expire (e.g.
                      OPERASource's local VRT paths) and is used as-is on
                      every attempt.
    overview_level  : int or None
                      Passed through to rioxarray.open_rasterio if given.
    masked          : bool
                      Passed through to rioxarray.open_rasterio.
    max_attempts    : int
                      Number of attempts before raising the last error.
    backoff_seconds : int
                      Delay between attempts.
    bbox            : (minx, miny, maxx, maxy) or None
                      If given, in the SAME CRS as the raster being
                      opened (the caller is responsible for reprojecting
                      -- this function has no way to know a remote
                      href's CRS before opening it), clips to this
                      window BEFORE materializing pixel data, so a COG's
                      internal tiling means only the intersecting tiles
                      are actually fetched over the network (measured:
                      ~540x fewer bytes for a 5km AOI window vs. a full
                      ~1.86GB Sentinel-1 RTC scene -- see
                      MPCSource.read_vv_vh(), the only current caller).
                      None (default) reads the full extent, unchanged
                      from this function's original behavior -- what
                      OPERASource's local VRT path still uses, since
                      windowing only helps for a real remote COG.

    Returns
    -------
    xarray.DataArray
    """
    last_exc = None
    for attempt in range(1, max_attempts + 1):
        attempt_href = href() if callable(href) else href
        try:
            with rasterio.Env(**GDAL_HTTP_ENV):
                kwargs = {'masked': masked}
                if overview_level is not None:
                    kwargs['overview_level'] = overview_level
                # rioxarray.open_rasterio() returns a lazy handle -- the
                # actual pixel data isn't fetched until something forces
                # it (e.g. decibel_to_linear()'s arithmetic much later,
                # possibly on a different thread, or .rio.clip_box()
                # below, or the final .load()). A transient read
                # failure at that point (e.g. a dropped connection
                # mid-transfer -- TIFFFillTile: got 0 bytes, expected N)
                # would happen entirely outside this function's retry
                # loop and go unretried. Force the read here, inside the
                # loop, so transient failures are caught and retried
                # exactly like a failed open() would be.
                da = rioxarray.open_rasterio(attempt_href, **kwargs)
                if bbox is not None:
                    # Still lazy: clip_box() only narrows the x/y
                    # coordinate selection on the not-yet-materialized
                    # array. Only the .load() below actually triggers
                    # GDAL to fetch data -- scoped to this narrower
                    # selection, i.e. only the COG tiles intersecting
                    # bbox, via HTTP range requests.
                    minx, miny, maxx, maxy = bbox
                    da = da.rio.clip_box(minx, miny, maxx, maxy)
                return da.load()
        except Exception as exc:
            last_exc = exc
            if attempt < max_attempts:
                # Exponential backoff (20s, 40s, 80s, 160s...) rather than
                # a flat delay -- a wave of many 403s across many
                # concurrent tiles in a short window looks like MPC-side
                # throttling under heavy anonymous load, not a one-off
                # blip, so a longer runway between attempts gives a real
                # throttle window a chance to clear instead of just
                # hammering it again 10-20s later.
                wait = backoff_seconds * (2 ** (attempt - 1))
                logger.warning(
                    f"Attempt {attempt}/{max_attempts} to open {attempt_href} failed "
                    f"({exc!r}); retrying in {wait}s."
                )
                time.sleep(wait)
            else:
                logger.warning(
                    f"Attempt {attempt}/{max_attempts} to open {attempt_href} failed "
                    f"({exc!r}); giving up."
                )
    raise last_exc


# this function creates python datetime objects using a given date and number of days to advance
def date_range(start, days):
    """
    Inclusive [start, start + days] range, e.g. date_range('01/08/2023', 10)
    covers Aug 1-11. `start` is 'dd/mm/yyyy'.
    """
    temp_date = pd.date_range(datetime.datetime.strptime(start, '%d/%m/%Y'), periods=days+1, freq='D')

    return (temp_date.min().date(), temp_date.max().date())


# define a function to format string correctly and create date range
def string_to_date_range(start, end):
    """
    Expand 'yyyy/mm' month strings into a (first day, last day) date range,
    e.g. ('2024/07', '2024/07') -> (2024-07-01, 2024-07-31). Handles
    December correctly (end_month % 12 + 1 wraps to January of the next
    calendar year to compute the day count, not the returned date itself).
    """
    start_year, start_month = start.split('/')
    end_year, end_month = end.split('/')

    delta_days_end = (datetime.date(int(end_year), int(end_month) % 12 + 1, 1) - datetime.timedelta(days=1)).day

    return (
        datetime.datetime.strptime(f'01/{start_month}/{start_year}', '%d/%m/%Y').date(),
        datetime.datetime.strptime(f'{delta_days_end:02d}/{end_month}/{end_year}', '%d/%m/%Y').date()
    )

# define a function to get bounding box as json from a shapefile using GeoPandas
def gpd_to_json(id_list, infile, separate=True, id_key='ID', zone_key='zone', buffer=None):
    """
    Read `infile`, filter to `id_list`, and return each polygon's bounding
    box (not its exact shape) as a GeoJSON-like dict -- the shape a
    STACSource.search_sentinel1()/search_dem() call expects for its bbox.

    separate=False collapses every matched polygon into one combined
    bbox instead of one per polygon, with a placeholder `id_key` of 1 --
    used to build a single search area covering several AOIs at once
    (see flood_mapper.aoi_union). separate=True (default) is one bbox per
    AOI, each tagged with its real ID and UTM zone.

    buffer, if given, is applied in the tile's own UTM zone (meters) before
    reprojecting back to WGS84 -- used only for DEM download, where slope
    needs a slightly larger footprint than the AOI itself so the edge
    pixels of the kernel-based slope calculation aren't starved of
    neighbors.
    """
    # create GeoJSON using the bounds
    def get_bbox(bbox):
        lon_min, lat_min, lon_max, lat_max = bbox

        return [
            [lon_min, lat_min],
            [lon_max, lat_min],
            [lon_max, lat_max],
            [lon_min, lat_max],
            [lon_min, lat_min]
        ]


    # read the shapefile
    gdf = gpd.read_file(infile)
    
    # filter using the given ID list
    gdf = gdf.loc[gdf[id_key].isin(id_list)]

    # if buffer parameter is passed, reproject to local, then buffer and preproject back to wgs84
    # this is the case only for downloading DEM because we need slope for a slightly bigger region to run kernel
    if buffer:
        tile_utm_zone = zone_to_epsg(gdf['zone'].values[0])
        gdf = gdf.to_crs(tile_utm_zone)
        gdf['geometry'] = gdf.buffer(buffer).to_crs('EPSG:4326')
    
    # extract bounding box of each of the filtered polygons
    if separate == True:
        gdf_bbox = [
            (row[id_key], row[zone_key], row.geometry.bounds)
            for idx, row in gdf.iterrows()
                   ]

        return [{
            "type": "Polygon",
            "coordinates": [
                get_bbox(bounds_item)
            ],
            "properties": {
                id_key: id,
                zone_key: zone
            }
        }
            for id, zone, bounds_item in gdf_bbox
        ]

    else:
        gdf_bbox = [(1, gdf.total_bounds)]

    
        return [{
            "type": "Polygon",
            "coordinates": [
                get_bbox(bounds_item)
            ],
            "properties": {
                id_key: id
            }
        }
        for id, bounds_item in gdf_bbox
        ]

# define a function to search for Sentinel-1 data
def search_sentinel_data(bbox, start_date=None, end_date=None):
    """
    Deprecated: thin backward-compatible wrapper around
    autofloods.sources.MPCSource().search_sentinel1(). New code should use
    an autofloods.sources.STACSource implementation directly (autofloods
    injects one into flood_mapper via its `source` argument) rather than
    calling this function.
    """
    from ..sources import MPCSource

    return MPCSource().search_sentinel1(bbox, start_date, end_date)

## define a function to get footprint of a given S1 item
def s1item_footprint(item):
    """
    One-row GeoDataFrame (columns 'ID', 'geometry', CRS EPSG:4326) for a
    STAC item's own footprint polygon -- not the AOI's. Used by
    seggregate_sentinel_search() to test scene/AOI intersection.
    """
    polygon = Polygon(item.geometry['coordinates'][0])

    return gpd.GeoDataFrame({'ID':item.id, 'geometry': [polygon]}, crs='EPSG:4326')

# define a function that calls the above function for a given ID list but separates the search items for each given ID
def seggregate_sentinel_search(aoi_list, search_items):
    """
    Cross-reference search results against AOI footprints (real polygon
    intersection, not just bbox overlap) to answer two questions at once:
    which scenes cover each AOI, and which AOI(s) each scene covers.
    Needed because one STAC search can span multiple AOIs at once (see
    flood_mapper.aoi_union) whose bboxes may overlap without every scene
    actually covering every AOI.

    Parameters
    -----------
    aoi_list        : AOI polygons in GeoJSON-like format (as returned by gpd_to_json).
    search_items    : (unused_first_element, list_of_stac_items) -- matches the
                      shape flood_mapper.get_s1_items() builds; only the second
                      element is read.

    Returns
    -------
    (aoi_scene_dict, scene_aoi_dict) : aoi_scene_dict maps each AOI ID (int) to
        the list of intersecting scene IDs; scene_aoi_dict maps each scene ID to
        the list of intersecting AOI IDs (int). If search_items has no results
        (e.g. every AOI's dry-season baseline was already complete, so nothing
        needed searching), returns every AOI mapped to an empty list rather than
        raising on pd.concat([]).
    """
    # create GDF from the AOI list
    aoi_footprints = gpd.GeoDataFrame([
        {'ID': aoi['properties']['ID'], 'geometry': Polygon(aoi['coordinates'][0])}
        for aoi in aoi_list],
        crs='EPSG:4326'
    )

    if not search_items[1]:
        # No search results at all -- e.g. every requested AOI already had
        # a completed dry-season baseline, so generate_dry_date_ranges()
        # produced an empty date range and the STAC search found nothing
        # to do (see flood_mapper.generate_dry_date_ranges). pd.concat([])
        # below would raise "No objects to concatenate" on an empty list;
        # every AOI simply maps to zero intersecting scenes instead.
        empty_aoi_scene_dict = {int(row['ID']): [] for _, row in aoi_footprints.iterrows()}
        return empty_aoi_scene_dict, {}

    # create GDF from the stac items list
    s1_footprints = pd.concat([s1item_footprint(item) for item in search_items[1]], axis=0)

    # create two dictionary to store two way information
    aoi_scene_dict = {}
    scene_aoi_dict = {}

    # loop through AOI polygons to find intersecting scenes IDs
    for idx, row in aoi_footprints.iterrows():
        intersecting_s1scene_ids = s1_footprints[row.geometry.intersects(s1_footprints.geometry)]['ID'].values

        # Converting key to int because JSON export causes problems
        # with numpy integer data types while exporting json.
        aoi_scene_dict[int(row['ID'])] = [item.id for item in search_items[1] if item.id in intersecting_s1scene_ids]

    # loop through scenes IDs to find intersecting AOI polygons
    for idx, row in s1_footprints.iterrows():
        intersecting_aoi_ids = aoi_footprints[row.geometry.intersects(aoi_footprints.geometry)]['ID'].values

        # Converting items to int inside list comprehension because JSON export causes problems
        # with numpy integer data types while exporting json.
        scene_aoi_dict[row['ID']] = [int(item) for item in list(intersecting_aoi_ids)]

    return aoi_scene_dict, scene_aoi_dict

def query_nasadem(aoi_union_bbox):
    """
    Deprecated: thin backward-compatible wrapper around
    autofloods.sources.MPCSource().search_dem(). New code should use an
    autofloods.sources.STACSource implementation directly.
    """
    from ..sources import MPCSource

    return MPCSource().search_dem(aoi_union_bbox)

def download_nasadem(bbox, source, overview_level=1, nodata=0.0, max_workers=6):
    """
    Search + read every DEM tile covering `bbox` and mosaic them into one
    DataArray (rioxarray_merge.merge_arrays -- last-tile-wins on overlap).
    `nodata` is the mosaic's fill value where no DEM tile covers a pixel,
    not a value found in the source data itself.

    max_workers concurrent reads for the same I/O-bound reasons as
    flood_mapper.read_scenes() -- see the comment there. This is a
    network-concurrency knob (tuned against the data source's own rate
    tolerance), not a CPU-bound one, so unlike the reprojection thread
    pools it is NOT derived from local CPU count (utils.default_max_workers) --
    a fast multi-core machine on a rate-limited connection still needs a
    modest, source-tuned value here, not one that scales with cores.
    """
    dem_item_list = source.search_dem(bbox)
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        dem_xarray_list = list(executor.map(
            lambda item: open_rasterio_with_retry(source.dem_href(item), overview_level=overview_level, masked=True),
            dem_item_list,
        ))

    mosaic_xarray = rioxarray_merge.merge_arrays(dem_xarray_list, nodata=nodata)

    return mosaic_xarray

# define a function to export xarray.DataArray object to TIFF file
def export_xarray(xarray_data, filename, bandnames=None):
    """
    Write a DataArray to `filename` as a Cloud Optimized GeoTIFF (COG) --
    tiled, DEFLATE-compressed, with internal overviews auto-built by
    GDAL's COG driver (skipped for rasters too small to benefit, which is
    expected/harmless, not a bug). Bounds/transform are computed from
    `xarray_data`'s own x/y coordinates. This is the single choke point
    for every raster this package writes (slope, per-scene flood rasters,
    merged-by-date stacks, scene counts) -- change compression/tiling
    settings here, not per-caller.

    Only 2D (y, x) and 3D (band, y, x) `xarray_data` is supported.

    Parameters
    ----------
    xarray_data                 : The Xarray dataset or data array to be exported.
    filename                    : The path and filename of the output GeoTIFF file.
    """
    # NOTE: only 2D/3D xarray_data is actually handled below -- other
    # dimensionalities hit a broken error path (this print(), then a
    # NameError on undefined rows/cols building `profile` a few lines
    # down, not a clean exception). Not fixed here (doc-only pass); pass
    # exactly 2D or 3D data.
    # Ensure the output directory exists rather than assuming it does --
    # a fresh/rebuilt output tree, or a resumed run whose output_dir
    # moved, shouldn't crash here with a bare "No such file or directory"
    # from GDAL.
    out_dir = os.path.dirname(filename)
    if out_dir and not os.path.exists(out_dir):
        os.makedirs(out_dir, exist_ok=True)

    with rasterio.Env():
        xmin, ymin, xmax, ymax = [
            xarray_data.x.min().values,
            xarray_data.y.min().values,
            xarray_data.x.max().values,
            xarray_data.y.max().values
        ]

        if len(xarray_data.dims) == 3:
            bands, rows, cols = xarray_data.shape
        elif len(xarray_data.dims) == 2:
            rows, cols = xarray_data.shape
        else:
            print('Number of dimensions in input data exceed three. Please check.')

        # Define the metadata for the output file
        profile = {
            'driver': 'COG',
            'dtype': rasterio.float32,
            'nodata': np.nan,
            'width': cols,
            'height': rows,
            'count': xarray_data.shape[0] if len(xarray_data.dims) == 3 else 1,
            'transform': rasterio.transform.from_bounds(xmin, ymin, xmax, ymax, cols, rows),
            # float32 data -> horizontal-differencing predictor 3 (not 2,
            # which is for integer data and compresses float32 worse).
            'compress': 'DEFLATE',
            'predictor': 3,
            # 'nearest' never introduces values outside the original data
            # range in the overview pyramid -- a safe default across every
            # caller of this function, whether the array is continuous
            # (slope, mean/std) or effectively categorical (flood class
            # rasters, scene counts), without needing per-caller tuning.
            'overview_resampling': 'nearest',
        }

        with rasterio.open(
                filename,
                'w', **profile) as dst:
            # if input array is 2D
            if len(xarray_data.dims) == 2:
                dst.write(xarray_data.data, 1)
            # if input data is 3D
            elif len(xarray_data.dims) == 3:
                for band in range(xarray_data.shape[0]):
                    dst.write(xarray_data.data[band, :, :], band+1)
            else:
                raise('InputDataDimensionError: Unexpected number of dimensions found in the input data.')

            if bandnames:
                for n, item in enumerate(bandnames):
                    dst.set_band_description(n+1, item)


# define a function to convert numpy array to xarray object using a reference xarray object
def numpy_to_xarray(numpy_data, ref_xarray):
    """
    Wrap a plain NumPy array (2D, or 3D as band-first) in a georeferenced
    DataArray, copying CRS/transform/coords/attrs from `ref_xarray`. Used
    after a NumPy-level computation (e.g. slope, a detector's raw output)
    needs to become a proper raster again. `numpy_data`'s spatial shape
    must match `ref_xarray`'s -- this does not resample or reproject.
    3D input gets auto-named bands ('Band1', 'Band2', ...); pass real
    names via export_xarray()'s `bandnames` at write time instead if
    that matters for the output file.
    """
    # Validate spatial dimensions
    if len(numpy_data.shape) not in [2, 3]:
        raise ValueError("Input NumPy array must be 2D or 3D.")

    # Get the geospatial information from the reference xarray object
    transform = ref_xarray.rio.transform()
    crs = ref_xarray.rio.crs

    # Create band names for 3D NumPy array
    band_names = [f'Band{i+1}' for i in range(numpy_data.shape[0])] if len(numpy_data.shape) == 3 else None

    # Create an xarray DataArray with geospatial information and bands using rioxarray
    if band_names:
        xarray_data = xr.DataArray(data=numpy_data, dims=['band', *ref_xarray.dims], coords={'band': band_names, **ref_xarray.coords}, attrs=ref_xarray.attrs)
    else:
        xarray_data = xr.DataArray(data=numpy_data, dims=ref_xarray.dims, coords=ref_xarray.coords, attrs=ref_xarray.attrs)

    xarray_data.rio.write_crs(crs)
    xarray_data.rio.write_transform(transform)

    return xarray_data


# define a function to merge the exported flood extent file using date
def merge_flood_gdfs(flood_dir, date_index=5, delimiter='_'):
    """
    Merge every per-scene flood-vector .gpkg in `flood_dir` into one
    dissolved-by-(tile, date) GeoDataFrame per tile, written to
    '<flood_dir with flood_vector -> final_output>/{dry_years}_{tile_id}_FloodExtent.gpkg'.

    NOTE: `date_index`/`delimiter` parse the date and tile ID out of each
    filename by fixed underscore-position (tokens [4] and [5]), matching
    MPC-sourced scene ID naming only -- unlike combine_flood_dates()
    elsewhere in this module, this function was not updated for OPERA's
    shorter "OPERA_PASS_{date}"-derived filenames and will likely mis-parse
    or throw an IndexError on them. Not currently exercised by the
    production OPERA path (map_floods()'s export_vector defaults to False),
    but fix this the same way as _extract_date_token() before enabling
    vector export against OPERA output.
    """
    # get the list of files present in the directory
    files_list = glob.glob(f'{flood_dir}/*.gpkg')

    # extract unique dates from the flood vector file names
    unique_dates = [os.path.split(file)[-1].split(delimiter)[date_index-1][:8] for file in files_list]

    # merge
    gdf_union = pd.concat([
        gpd.read_file(file).assign(id=[file] * gpd.read_file(file).shape[0])
        for file in files_list
    ], axis=0)

    # dissolve flood extent shapefile
    gdf_union['date'] = gdf_union.id.apply(lambda x: x.split('_')[5][:8])
    gdf_union['tile_id'] = gdf_union['id'].apply(lambda x: x.split('_')[4])
    gdf_union['uid'] = gdf_union['tile_id'] + '_' + gdf_union['date']
    dry_years = gdf_union.id.apply(lambda x: '_'.join(x.split('_')[2:4])).values[0]

    # dissolve
    gdf_union = gdf_union.dissolve('uid')[['geometry', 'date', 'tile_id']]

    # export tile wise flood extent
    for tile_id in gdf_union['tile_id'].unique():
        temp_gdf = gdf_union.loc[gdf_union['tile_id'] == tile_id]

        outfile = os.path.join(
            flood_dir.replace('flood_vector', 'final_output'),
            f'{dry_years}_{tile_id}_FloodExtent.gpkg'
        )

        temp_gdf.to_file(outfile)



def decibel_to_linear(decibels):
    """dB -> linear power. Sentinel-1 RTC backscatter is stored in dB;
    the Z-score baseline (mean/std) is computed in linear units, since
    averaging in dB (a log scale) would bias the mean. See linear_to_decibel
    for the inverse, used only for display (e.g. plotting VV/VH imagery)."""
    return 10 ** (decibels / 10)


def linear_to_decibel(linear):
    """Linear power -> dB. Inverse of decibel_to_linear(); use for display
    only -- the pipeline itself works in linear units end to end."""
    return 10 * np.log10(linear)


_DATE_TOKEN_RE = re.compile(r'^\d{8}')


def _extract_date_token(key, date_index=-5):
    """
    Extract the YYYYMMDD date from a scene/pass ID or filename.

    Tries date_index first -- this matches MPC's underscore-separated
    token layout (..._{YYYYMMDDTHHMMSS}_...) positionally, and is kept as
    the first attempt so MPC's well-tested behavior is completely
    unchanged. Falls back to scanning all underscore-separated tokens for
    the first one starting with 8 digits when date_index is out of range
    or doesn't land on a date-shaped token -- this covers OPERA's shorter
    "OPERA_PASS_{YYYYMMDD}" IDs (3 tokens; -5 is out of range for them)
    without threading per-source ID-shape knowledge into this function.
    """
    tokens = key.split('_')
    if -len(tokens) <= date_index < len(tokens):
        candidate = tokens[date_index]
        if _DATE_TOKEN_RE.match(candidate):
            return candidate[:8]
    for token in tokens:
        if _DATE_TOKEN_RE.match(token):
            return token[:8]
    raise ValueError(f"Could not find an 8-digit date token in {key!r}")


def combine_flood_dates(flood_data, date_index=-5):
    """
    Collapse same-date scenes into one flood layer per date, taking the
    per-pixel maximum across scenes (np.maximum.reduce) -- so a pixel
    flagged flooded (class 3, see detectors.ZScoreDetector) by ANY scene
    on a given date stays flooded in that date's combined layer, even if
    other same-date scenes disagree.

    Parameters
    ----------
    flood_data : dict[str, xarray.DataArray] or list[str]
        Either {scene_id: classified_array} (in-memory, from map_floods()),
        or a list of paths to already-exported classified .tif files.
    date_index : int
        Passed through to _extract_date_token() -- see its docstring for
        how the date is located in each key/filename.

    Returns
    -------
    dict[str, numpy.ndarray] : YYYYMMDD date -> combined 2D array.
    """
    data_dict = None

    # the input flood data can either be a dictionary of xarray objects
    if type(flood_data) == type(dict()):
        unique_dates = sorted(set(
            [
                _extract_date_token(key, date_index)
                for key in flood_data
                ]
        ))

        data_dict = {
            u_date: np.maximum.reduce([
                flood_data[key].to_numpy()
                for key in flood_data
                if _extract_date_token(key, date_index) == u_date
            ])
            for u_date in unique_dates
        }

        return data_dict

    # or it can be a list of paths to geotiff files
    elif type(flood_data) == type(list()):
        unique_dates = sorted(set(
            [
                _extract_date_token(file, date_index)
                for file in flood_data
                ]
        ))

        data_dict = {
            key: np.maximum.reduce([
                rasterio.open(filepath).read(1)
                for filepath in flood_data
                if _extract_date_token(filepath, date_index) == key
            ])
            for key in unique_dates
        }

        return data_dict

    else:
        raise TypeError("Only dictionary containing xarray objects or list containing .tif file paths are supported.")


def flood_data_3dstack(flood_data, date_index=-5):
    """
    combine_flood_dates() + stack into one 3D array (date, y, x). Assumes
    every entry in `flood_data` belongs to the same tile (mixed-tile input
    will silently stack misaligned grids). Returns (dates, stack) where
    dates[i] labels stack[i] -- see merge_floods_by_date(), the caller
    that turns this into the DataArray written to floodextentstacked_*.tif.
    """
    # call the function that neatly combines flood maps for different dates
    data_dict = combine_flood_dates(flood_data, date_index=date_index)


    # for now let's say every non-zero cell is flood
    # stack all of them in a 3D array with cell value as date
    return list(data_dict.keys()), np.stack([
        data_dict[key]
        for key in data_dict
        ])
